name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        redmine: ["4.2", "5.0"]
        db: ["sqlite", "mysql", "postgresql"]
        include:
          - ruby: "2.7"

    name: "Ruby ${{ matrix.ruby }} / Redmine ${{ matrix.redmine }} / ${{ matrix.db }}"

    steps:
      - name: Execute tests
        uses: eXolnet/action-redmine-plugin@v2
        with:
          plugin_name: "redmine_wbs"
          redmine_version: "${{ matrix.redmine }}"
          ruby_version: "${{ matrix.ruby }}"
          database: "${{ matrix.db }}"

  assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and build assets
        run: |
          npm install
          npm run production
