name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        redmine: ["3.4", "4.0", "4.1"]
        db: ["sqlite", "mysql", "postgresql"]
        include:
          - ruby: "2.4"

    name: "Ruby ${{ matrix.ruby }} / Redmine ${{ matrix.redmine }} / ${{ matrix.db }}"

    steps:
      - name: Execute tests
        uses: eXolnet/action-redmine-plugin@v1
        with:
          plugin_name: "redmine_wbs"
          redmine_version: "${{ matrix.redmine }}"
          ruby_version: "${{ matrix.ruby }}"
          database: "${{ matrix.db }}"

  assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Yarn
        run: |
          corepack enable yarn
          corepack prepare yarn@stable --activate

      - name: Install and build assets
        run: |
          yarn install
          yarn run production
